### ISSUE TITLE
Update GitHub link

### ISSUE THREAD

**Issue by davidaylaian** [CHSGraphics/Centennial-Graphics-Site#24]
The GitHub link in the footer points to the old repository location.

![screenshot](https://user-images.githubusercontent.com/22228595/31203213-1456c5cc-a934-11e7-8992-a34c84f52edd.png)

Update the link to point to [https://github.com/CHSGraphics](https://github.com/CHSGraphics) instead. Remember that the link is in all 5 html files, so don't forget to update the link on any of them!

**Comment by sikamsikam** [comment]
I have changed the code, committed, pulled from master branch, and pushed to github-footer-link. What do I do next to send it for review?

**Comment by davidaylaian** [comment]
@sikamsikam I private messaged you saying what you need to do.

**Comment by sikamsikam** [comment]
Thank you. I will take a look at it.
